### ISSUE TITLE
Bypass Amazon protection

### ISSUE THREAD

**Issue by frbelotto** [python-scrapy-playbook/amazon-python-scrapy-scraper#3]
Hello!
Your video and your code is amazing, simple and functional.
What I´ve observed is that Amazon is blocking my scraping attempt :

![image](https://github.com/python-scrapy-playbook/amazon-python-scrapy-scraper/assets/24688087/a8de78d8-ea20-42d2-8a18-0796ada6364f)

I´ve been reading that setting a different User Agent could help.

Could you please update or instruct how could I insert a new "user agent" inside your script?

Best regards,

**Comment by josephkearney91** [comment]
Hi there,

You can read more about the User Agent integrations in our documentation here:
https://scrapeops.io/docs/fake-user-agent-headers-api/integrations/python-scrapy/

However - if you are doing any sort of medium/large scrape scraping you would need to use a proxy which would rotate the IP address as well as the headers. You can read on how to set this up here:
https://scrapeops.io/docs/proxy-aggregator/integration-examples/python-scrapy-example/#scrapeops-scrapy-proxy-sdk-installation

I hope that helps!
